library(MutationalPatterns)
library(tidyverse)
library(GenomicRanges)
library(ComplexHeatmap)
library(reshape2)
library(gridExtra)
library(circlize)
library(BSgenome)
library(VariantAnnotation)
library(lsa)
library(stringi)
library(ggseqlogo)
library(readr)
library(vegan)
library(ade4)
library(stringr)
library(ggplot2)


rm(list=ls(all=TRUE))

ref_genome='BSgenome.Mmusculus.UCSC.mm10'
vcf_files <- read.table("vcflist")
sample_names <- read.table("samplenames")
vcf <- read_vcfs_as_granges(as.character(vcf_files[,1]), as.character(sample_names[,1]), ref_genome)
edit_mat=edit_matrix(vcf,ref_genome=ref_genome)
explot<-plot_192_edit_profile(edit_mat,ymax=0.15)
save.image(file="example.rda")
save(vcf, file="vcf.rda")
save(edit_mat, file="edit_mat.rda")
